apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-java-quarkus-mxctblfx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/backend-tests-java-quarkus-mxctblfx:21aee560620522cd71070552b025d3a29070a9f4@sha256:400ef12c87c267dcd4e42d98e62a3695017f0699eb300bcce7de57615b29980f
          name: container-image
