apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-java-quarkus-mxctblfx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/backend-tests-java-quarkus-mxctblfx:85987250bee980fb5a1677c9f770ce2e4db41b1b@sha256:15674b043e36991a61b3cef4e6b84008d4046f8d30b7a1274d1c218ee82606e7
          name: container-image
